blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views






urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('login/', auth_views.LoginView.as_view(template_name='login_old.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
   


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from .views import PostListView, PostDetailView, PostCreateView, PostDeleteView, PostUpdateView, CommentCreateView,trial, CategoryDetailView

app_name = 'posts'

urlpatterns = [
  
  path('posts/', PostListView.as_view(), name='post-list'),
  path('posts/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
  path('posts/create/', PostCreateView.as_view(), name='post-create'),
  path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
  path('posts/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
  path('posts/<int:pk>/comment/', CommentCreateView.as_view(), name='post-comment'),
  path('posts/category/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
  path('index/', trial),

 
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy





class Category(models.Model):
	title = models.CharField(max_length=20)

	class Meta:
		verbose_name_plural='Categories'

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse ('posts:category-detail', kwargs={'pk':self.pk})
		



class Author(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.user.username


class Posts(models.Model):
	title = models.CharField(max_length=100)
	text = models.TextField()
	timestamp = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(Author, on_delete=models.CASCADE)
	categories = models.ManyToManyField(Category)

	class Meta:
		verbose_name_plural="Posts"

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('posts:post-detail', kwargs={'pk':self.pk})

	def get_update_url(self):
		return reverse('post-update', kwargs={'pk':self.pk})

	def get_delete_url(self):
		return reverse('post-delete', kwargs={'pk':self.pk})






class Comments(models.Model):

	textarea = models.TextField()
	created_by = models.ForeignKey(Author, on_delete=models.CASCADE)
	timestamp = models.DateTimeField(auto_now_add=True)
	post = models.ForeignKey(Posts, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural='Comments'

	def __str__(self):
		return self.textarea

	def get_absolute_url(self):
		return reverse('posts:post-comment', kwargs={'pk':self.pk})
	



	
	






		

	

	
        

posts/forms.py
from django.forms import ModelForm


from .models import Posts, Comments

class PostForm(ModelForm):

	class Meta:
		model = Posts
		fields = "__all__"

class CommentForm(ModelForm):

	class Meta:
		model = Comments
		fields = ['textarea']		

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy

from posts.models import Posts, Comments, Author, Category
from .forms import PostForm



class PostListView(ListView):
	model = Posts
	template_name = 'posts_list.html'

	def get_context_data(self, **kwargs):
		categories = Category.objects.all()
		latest = Posts.objects.order_by('-timestamp')[0:3]
		context = super().get_context_data(**kwargs)
		context['categories'] = categories
		context['latest'] = latest
		return context
        


class PostDetailView(DetailView):
	model = Posts
	template_name = 'posts_detail.html'
	
	


	def get_context_data(self, **kwargs):
		post = self.get_object()
		comments = Comments.objects.filter(post=post)
		categories = Category.objects.all()
		latest = Posts.objects.order_by('-timestamp')[0:3]
		kwargs['comments'] = comments
		kwargs['categories'] = categories
		kwargs['latest'] = latest

		return super().get_context_data(**kwargs)

	
@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
	model = Posts
	template_name = 'posts_form.html'
	fields = ['title', 'text', 'categories']

	def form_valid(self, form):
		post = form.save(commit=False)
		usr = get_object_or_404(Author, user=self.request.user)
		print (usr)
		post.author = usr
		post.save()
		return redirect('posts:post-list')






class PostUpdateView(UpdateView):
	model = Posts
	template_name = 'posts_form.html'
	fields = ['title', 'text','author', 'categories']	



class PostDeleteView(DeleteView):
    model = Posts
    template_name = 'posts_confirm_delete.html'	
    success_url = ('/posts/')



def trial(request):			
	return render (request, "index.html")



@method_decorator(login_required, name='dispatch')
class CommentCreateView(CreateView):
	model = Comments
	template_name = 'comment_form.html'
	fields = ['textarea']


	def form_valid(self, form):
		post = Posts.objects.get(pk=self.kwargs['pk'])
		athr = Author.objects.get(user=self.request.user)
		comment = form.save(commit=False)
		comment.created_by = athr
		comment.post = post
		comment.save()
		return redirect('posts:post-detail', self.kwargs['pk'])
	
	# def get_success_url(self):
	# 	return reverse ('posts:post-detail', kwargs={'pk':self.kwargs['pk']})




class CategoryDetailView(DetailView):
	model = Category
	template_name = 'category_detail.html'

	def get_context_data(self, **kwargs):
		cat = self.get_object()
		posts = Posts.objects.filter(categories=cat)
		kwargs['posts'] = posts
		return super().get_context_data(**kwargs)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Post - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/blog-post.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:post-list' %}">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Logout
              <span class="sr-only">(current)</span>
            </a>
            {%else %}

             <a class="nav-link" href="{% url 'login' %}">Login
              <span class="sr-only">(current)</span>
            </a>

            {% endif %}
          </li>
         {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:post-create' %}">Create</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

 <div class="container">

    <div class="row">

      <!-- Post Content Column -->
     




{% block content%}  {% endblock%}



  
 
       


  
       
   



  






   {% block sidebar %} 

   {% endblock %}



    



    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
{% block footer %}
  <!-- Footer -->
 
    <!-- /.container -->
  </footer>

 {% endblock%} 

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/category_detail.html
{% extends "base.html" %}


{% block content %}

{% for post in posts %}

<p>{{post.title}}</p></br>

{% endfor%}

{% endblock %}

templates/comment_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content%}

 <div class="col-sm-2">
     
    </div>
 <div class="col-sm">

 	<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Create comment</li>
  </ol>
</nav>
<form method="post" class="mb-4" novalidate >
	{% csrf_token %}
    {{form | crispy}}
    <button type="submit" class="btn btn-primary btn-block">Save</button>
</form>
</div>

  <div class="col-sm-2">
     
    </div>

{% endblock%}

   
      One of three columns
    
  

templates/footer.html
 {% block footer %}

 <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>

{% endblock %}    <!-- /.c

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Post - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/blog-post.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
     

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Log in to Django Boards{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {{form | crispy}}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          New to Django Boards? <a href="{% url 'posts:post-list' %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="{% url 'posts:post-list' %}" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}


 
       









 <!-- Bootstrap JavaScript -->


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

</body>
</html>

templates/login_old.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content%}

<div class="col-sm-2">
	
</div>
<div class="col-sm">
<nav aria-label="breadcrumb ">
  <ol class="breadcrumb mt-1">
    <li class="breadcrumb-item active" aria-current="page">Login</li>
  </ol>
</nav>
<form method="post" class="mb-4" novalidate >{% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-primary btn-block" type="submit">Login</button>
</form>
</div>
<div class="col-sm-2">
	
	</div>


{% endblock%}

templates/logout.html
<p>You are loggd out</p>

templates/posts_confirm_delete.html
{% extends 'base.html' %}


{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>


{% endblock%}

templates/posts_detail.html
{% extends 'base.html' %}




{% block content %}
  <!-- Page Content -->
  <div class="col-lg-8">
        <!-- Title -->
        <h1 class="mt-4">{{object.title }}</h1>
        <!-- Author -->
        <p class="lead">
          by
          <a href="#">{{object.author.user.username}}</a>
        </p>
        <hr>
        <!-- Date/Time -->
        <p>{{object.timestamp}}{{object.created_by}}</p>
        <hr>

        {% if request.user.is_authenticated %}
        {% if request.user == object.author.user %}
        <p><a href="{% url 'posts:post-update' object.id %}">Update</a><a href="{% url 'posts:post-delete' object.id %}">Delete</a></p>
        <p></p>
        {% endif %}
        {% endif %}
        <p>{{object.text}}</p>
        <hr>

          <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
                {{object.frm}}
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

         <!-- Single Comment -->
         {% for comment in comments%}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.created_by}}</h5>
            
            {{comment.textarea}}
          </div>
        </div>
        {% endfor %}
      </div>

      {% endblock %}


         {% block sidebar %}
        {% include 'sidebar.html' %}
        {% endblock %}
 {% block footer %}
      {% include 'footer.html' %}
      {% endblock %}

templates/posts_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}



{% block content%}
<div class="col-2">
</div>

<div class="col-8">

	<nav aria-label="breadcrumb" class="mb-4">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Create post here</li>
  </ol>
</nav>
<form method="post"  novalidate>{% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-primary btn-block" type="submit">Submit</button>
</form>
</div>

<div class="col-2">
</div>



{% endblock%}

templates/posts_list.html
{% extends 'base.html' %}

{% block content %}
  <!-- Page Content -->

 <div class="col-lg-8">
 
        {% for obj in object_list%}
        <!-- Title -->
                <h1 class="mt-4">{{obj.title }}</h1>

        <!-- Author -->
                <p class="lead">
          by
          {{obj.author.user.username}} 
        </p>

        <hr>
        <!-- Date/Time -->
        <p class="text-muted">{{obj.timestamp}}</p>
        <hr>
      
        
        <!-- Preview Image -->
        <!-- Post Content -->
      
        <p>{{obj.text|truncatewords:40}}</p>
        
        <a href="{{obj.get_absolute_url}}">Read more ..</a>
        <hr>

        {% endfor%}
</div>

      {% endblock %}


      {% block sidebar %}

      {% include 'sidebar.html'  %}


      {% endblock %}

      {% block footer %}
      {% include 'footer.html' %}
      {% endblock %}



  

templates/sidebar.html
<div class="col-md-4"> 
 <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

       <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                 {% for cat in categories %}
                  <li>
                  <a href="{{cat.get_absolute_url}}">{{cat.title}}</a>
                  </li>
          {% endfor%}
                   
              </div>
         
            </div>
          </div>
        </div>
        
          <div class="card my-4">
          <h5 class="card-header">Latest</h5>
          <div class="card-body">
            {% for new in latest %}
                  <li>
                  <a href="{{new.get_absolute_url}}">{{new.title | truncatewords:10}}</a>
                  </li>
          {% endfor%}

          </div>
        </div>  
        </div> 

templates/test.html
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
     {{form.as_p}}
  <button type="submit" class="btn btn-success">Post</button>